header:
  schema-version: 2.0.0
  last-updated: "2025-01-01"
  last-reviewed: "2025-01-01"
  url: https://github.com/meshery/meshery-operator/.github/security-insights.yml
  comment: |
    This file contains the security insights information for the Meshery-Operator project.

project:
  name: meshery-operator
  administrators:
    - name: Sangram Rath
      affiliation: Meshery
      email: sangram.rath@gmail.com
      primary: true
  repositories:
    - name: meshery-operator
      url: https://github.com/meshery/meshery-operator
      comment: |
        Meshery-Operator.
  vulnerability-reporting:
    reports-accepted: true
    bug-bounty-available: false
