apiVersion: meshery.layer5.io/v1alpha1
kind: MeshSync
metadata:
  name: meshery-meshsync
  namespace: meshery
  labels:
    app: meshery
    component: controller
    version: v0.1.15
  annotations:
    meshery/component-type: management-plane
spec:
  size: 1
  broker:
    native:
      name: meshery-broker
      namespace: meshery
  config:
    listener-config: 
      log-stream:
        connection-name: meshsync-logstream  
        name: log-stream
        publish-to: "meshery.meshsync.logs"
      exec-shell:
        connection-name: meshsync-exec  
        name: exec-shell
        publish-to: meshery.meshsync.exec  
      request-stream:
        connection-name: meshsync-request-stream  
        name: request-stream
        subscribe-to: meshery.meshsync.request  

    pipeline-configs:
      local:
        - name: "replicasets.v1.apps"
          publish-to: "meshery.meshsync.core"
        -  name: "pods.v1."
           publish-to: "meshery.meshsync.core"	
        -  name: "services.v1."
           publish-to: "meshery.meshsync.core"						
        -  name: "deployments.v1.apps"
           publish-to: "meshery.meshsync.core"
        -  name: "statefulsets.v1.apps"
           publish-to: "meshery.meshsync.core"
      global: 
        - name:      "namespaces.v1."
          publish-to: "meshery.meshsync.core"
        - name:      "configmaps.v1."
          publish-to: "meshery.meshsync.core"						
        - name:      "nodes.v1."
          publish-to: "meshery.meshsync.core"